### ISSUE TITLE
Rename motion_retargeting_remocon as motion_retargeting

### ISSUE THREAD

**Issue by corot** [robotics-in-concert/rocon_android_apps#1]
So we keep coherent with our naming system:
- Remocon reefers to the muti-apps starter tool
- Individual android apps are named as their robot/concert counterpart; the distinction between android front-end and robot/concert stuff is provided by its location under android_apps, turtlebot_apps, etc.

**Comment by bit-pirate** [comment]
:ok_woman:

**Comment by stonier** [comment]
:see_no_evil:

**Comment by corot** [comment]
serious engineers.....

2013/11/12 Daniel Stonier notifications@github.com

**Comment by bit-pirate** [comment]
:neckbeard:

**Comment by corot** [comment]
:japanese_ogre:    ㅋㅋㅋㅋㅋㅋㅋ
